### ISSUE TITLE
Unwilling `table.unpack` behaviour when transpiling to Lua

### ISSUE THREAD

**Issue by OzelotVanilla** [crankscript/crankscript#20] opened 2024-11-11 07:35 UTC
# Current Situation

At least one function is being transpiled to `table.unpack` and then assigned by destructing statement. The *Playdate Simulator* gives such error at the log page:

```log
attempt to get length of a number value
stack traceback:
	[C]: in function 'table.unpack'
```

# Example

Using the [blank template](https://github.com/crankscript/template-blank) here as an example. This [line](https://github.com/crankscript/template-blank/blob/ca8e693a019e2a5981173465b0e070cc78e7ec2b/src/index.ts#L8):

```ts
const [width, height] = playdate.graphics.getTextSize(helloString);
```

Will be transpiled to this:

```lua
local width, height = table.unpack(playdate.graphics.getTextSize(helloString))
```

Even `getTextSize` has a return type of `LuaMultiReturn`, `table.unpack` is added. And, if it is being printed, two values are outputed. This leads to the error `attempt to get length of a number value` because only `167` is being unpacked by the function.

```lua
print(playdate.graphics.getTextSize(helloString))
-- Will get things like `167 20`.
```

# Possible Bug Found

Since I am new to *Playdate* and this project, I would like to suggest that *TypeScript to Lua* used in this project **might be malfunctioning**, because the **`LuaMultiReturn` cannot be proceed by transpiler**. I tried to find answers in the source code, but I could not find a solution. At first I thought it is the `LuaMultiReturn` causing the bug, but then I found this is NOT the reason.

At the end, I use these code to test if they can be correctly transpiled:

```ts
function getSizeDummy0(): [number, number] { return [167, 20] }
function getSizeDummy1(): LuaMultiReturn<[number, number]> { return [167, 20] }
function getSizeDummy2() { return $multi(167, 20) }
let [width0, height0] = getSizeDummy0()
let [width1, height1] = getSizeDummy1()
let [width2, height2] = getSizeDummy2()
```

This is what I got from [TypeScriptToLua Playground](https://typescripttolua.github.io/play#code/GYVwdgxgLglg9mABAcwKZQMowF6oCIgC2hAngAwAUAlAFyIDaYRARqgE4A0iThrbAuogDeiNuhBsk9AIwA2AOxcATGUEBfAFChIsBCnRZcBYiWnU6AGRABDALIgANrABK4yQB5GLdlx59+AHzCom5IACSEjrAUcoqIKlSImtrQ8EhomDj4RKRK1MFiUBLhkU4wMQrKZImaGg7oDADuMAAmUAAWZFztqDDI7VCqiAC8+plGOeTUdQ30zW3t0t29-VDSgqMZhtkmZlQzUE2tHct9Axtj28a51EA):

```lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
function getSizeDummy0(self)
    return {167, 20}
end
function getSizeDummy1(self)
    return 167, 20
end
function getSizeDummy2(self)
    return 167, 20
end
width0, height0 = table.unpack(getSizeDummy0(nil))
width1, height1 = getSizeDummy1(nil)
width2, height2 = getSizeDummy2(nil)
```

While this is what I got from this project. I guess `$multi` not working here is also related to the bug here (but this test environment does not have TypeScriptToLua installed):

```lua
local function getSizeDummy0(self)
    return {167, 20}
end
local function getSizeDummy1(self)
    return {167, 20}
end
local function getSizeDummy2(self)
    return _____24multi(nil, 167, 20)
end
local width0, height0 = table.unpack(getSizeDummy0(nil))
local width1, height1 = table.unpack(getSizeDummy1(nil))
local width2, height2 = table.unpack(getSizeDummy2(nil))
```

Thank you for reading my issue here. Hope it can be fixed soon.

**Comment by alberteddu** [comment] 2024-11-11 12:34
Hey @OzelotVanilla! Thanks a lot for your detailed report, I really appreciate it.

However, I cannot reproduce the issue you are facing. Do you have some more indication that can help me get the error you're seeing? Maybe a reproduction repository that you can provide?

I understood that you are getting the error from the blank template. I have tried to transpile just now and I am not getting "unpack" on the Lua side.

**Comment by OzelotVanilla** [comment] 2024-11-11 14:47
Guten Tag, @alberteddu. Thank you for your quick reply, danke.

This is the [repository](https://github.com/OzelotVanilla/PlaydateIssue20BugReproduceRepo) that I got this bug from. Hope this is not related to the special behaviour of macOS system.

The environment is as follow:

* Machine: MacBook Pro M1, 2020.
* OS: macOS 15.1 (24B83).
* SDK: Version 2.6.0 for macOS.

Thanks again for your quick reply.

**Comment by alberteddu** [comment] 2024-11-11 15:06
Thanks! I can in fact reproduce. I don't know what the root cause is yet, but it's because of `pnpm`. It works fine with `npm`. However, I would like the library to support all npm alternatives, so I will add this to my list of things to test 😄 

More updates will follow.

**Comment by alberteddu** [comment] 2024-11-11 15:45
This should be fixed now. The fix has been applied to the template repository. I have [added](https://github.com/crankscript/template-blank/commit/a7dfe08f2fb5e363eabf73955eb869ccfd8c862f) `lua-types` to `peerDependencies` which makes `pnpm` install it in `node_modules`, as opposed to `node_modules/.pnpm`. `TypescriptToLua` needs it there. 

I have also [updated](https://github.com/crankscript/template-blank/commit/6dfaba36a0e7a4340ee3daa4aed2df0f88fac064) the file `tsconfig.json` to include the 2.6.0 version of the types, you might want to do that too (I had forgotten to do it).

Once again, thanks for reporting!

**Closed by alberteddu** 2024-11-11 15:45 UTC
